### PR TITLE
Removes sinon and chai, Migration to Jest matchers

### PR DESCRIPTION
**Pull request by ayusharma**
#### What changed in this PR:

- Removes chai and sinon
- Migrate tests to use jest matchers.

~~Note: I am waiting https://github.com/trivago/melody/pull/100 to be merged to update changelog.~~

### CODE REVIEW

**Comment by pago** [comment]
@ayusharma would you be ok if we merge this after the stream API? We'd then need to also update the  new tests added there but I'd rather prefer to avoid a conflict on that PR.

**Comment by ayusharma** [comment]
@pago Sure 👍 Better to merge after melody-streams.

**Comment by pago** [comment]
@ayusharma `melody-streams` is now in. I think we can proceed with this change. :)

**Comment by ayusharma** [comment]
@pago Yes. It can be merged to master :)

**Comment by pago** [comment]
Did you migrate the tests within the new `melody-streams` package? I can't seem to spot them within the PR.

**Comment by ayusharma** [comment]
@pago Yes. Tests have been migrated to use Jest matchers by @krakenfuss in melody-streams.

**Pull request merged**
