### PR TITLE
Feature - throw an error in melody-redux's connect if no store found

### PR DESCRIPTION
**Pull request by btiwaree**
This PR adds an error message that will be thrown when no store is found within `findNextStore` function.
Currently, the `findNextStore` function returns `null` without an error, this causes js errors like `Cannot read property 'subscribe' of null` or `Cannot read property 'getState' of null`; this error will provide better context on why the error is being thrown.

### CODE REVIEW

**Comment by jamesb3ll** [comment]
Thanks @btiwaree 😃  Instead of returning `null` we could return an empty object so it doesn't break or if an error is intended we can throw an error instead of invariant? Also please run `yarn bundlesize` update the bundle size in the main `package.json`.

**Comment by pago** [comment]
@jamesb3ll It currently throws an error later on and I think that silently hiding the error would only add confusion. `invariant` raises an error but we'll need our Babel plugin to make sure that it doesn't affect code size too much (removes the error message).

**Comment by btiwaree** [comment]
@jamesb3ll I don't think returning an empty object will help with clearing up confusing regarding actual error :) @pago could you please point me to the direction (here or slack) as to how i can investigate more on keeping filesize in check within babel plugin. Thanks!

**Comment by efegurkan** [comment]
@btiwaree you need to find/write a babel plugin that removes invariant from the code. similar to the one we use to remove inline env variables.

**Comment by pago** [comment]
Instead of choosing the complex solution with `invariant` which would require a plugin and compiler level support, how about we just check using `process.env.NODE_ENV` and either include the error message or not?

I think having this improvement would be extremely valuable so let's try to get it merged, please.

Not sure who wants to take over the PR though, so let me call some people: @danielcaldas @btiwaree @jamesb3ll @krakenfuss @abertelle @btiwaree

**Comment by btiwaree** [comment]
@pago thanks for the feedback, I will update the PR later.

**Pull request closed without merging**
