### PR TITLE
Chore: Add Coveralls

### PR DESCRIPTION
**Pull request by efegurkan**
Add coveralls support for melody

### CODE REVIEW

**Comment by efegurkan** [comment]
For some reason jest refuses to collect coverage 🤔

**Comment by ayusharma** [comment]
@efegurkan I think` 'collectCoverage': true` is missing in Jest config.

https://facebook.github.io/jest/docs/en/configuration.html#collectcoverage-boolean

**Comment by efegurkan** [comment]
@ayusharma I pass it in the `test-travis` script as a CLI argument. I don't intend to collect coverage everywhere.

On the CI though it is somehow trying to run it and fails silently.

**Comment by ayusharma** [comment]
I just noticed that `--coverage` option. 😃

**Comment by ayusharma** [comment]
@efegurkan I also tried Travis integration on my fork but every time I was getting the `unknown` coverage issue.

After that, I gave a try to Circle CI and everything work as expected. Please find result here
https://circleci.com/gh/ayusharma/melody/2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by efegurkan** [comment]
@ayusharma Thanks I will give it a try!

**Pull request merged**
